# Generated by Django 6.0.1 on 2026-02-03 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Short bio or intro', null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
    ]
