# Generated by Django 6.0.1 on 2026-02-03 09:12

import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_candidateprofile_bio_candidateprofile_github_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_images/default.png', help_text='Profile picture (jpg, png, max 2MB)', null=True, upload_to=profiles.models.user_profile_image_path),
        ),
    ]
