# Generated by Django 6.0.1 on 2026-02-03 10:03

import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_candidateprofile_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateprofile',
            name='full_name',
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Profile picture', null=True, upload_to=profiles.models.user_profile_image_path),
        ),
    ]
