# Generated by Django 6.0.1 on 2026-02-04 16:29

import django.core.validators
import profiles.models
import profiles.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_remove_candidateprofile_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=profiles.models.user_resume_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx']), profiles.validators.validate_file_size_5mb]),
        ),
    ]
