# Generated by Django 6.0.1 on 2026-02-05 07:22

import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_candidateprofile_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=profiles.models.user_profile_image_path),
        ),
    ]
