# Generated by Django 6.0.1 on 2026-02-05 08:08

import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_consultantprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultantprofile',
            old_name='location',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='consultantprofile',
            old_name='specialization',
            new_name='designation',
        ),
        migrations.RemoveField(
            model_name='consultantprofile',
            name='experience_years',
        ),
        migrations.RemoveField(
            model_name='consultantprofile',
            name='github',
        ),
        migrations.RemoveField(
            model_name='consultantprofile',
            name='rate_per_hour',
        ),
        migrations.RemoveField(
            model_name='consultantprofile',
            name='skills',
        ),
        migrations.AlterField(
            model_name='consultantprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=profiles.models.consultant_profile_image_path),
        ),
    ]
