# Generated by Django 6.0.1 on 2026-02-04 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='meeting_status',
            field=models.CharField(choices=[('NOT_SCHEDULED', 'Not Scheduled'), ('SCHEDULED', 'Scheduled'), ('POSTPONED', 'Postponed'), ('COMPLETED', 'Completed')], default='NOT_SCHEDULED', max_length=20),
        ),
    ]
