# Generated by Django 6.0.1 on 2026-02-04 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_application_meeting_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='meeting_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='meeting_status',
            field=models.CharField(choices=[('NOT_SCHEDULED', 'Not Scheduled'), ('SCHEDULED', 'Scheduled'), ('POSTPONED', 'Postponed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='NOT_SCHEDULED', max_length=20),
        ),
    ]
